# Generated by Django 3.1 on 2022-10-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation_variation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='variation_price',
        ),
    ]
