# Generated by Django 3.1 on 2022-10-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_taxcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxcount',
            options={'verbose_name': 'taxcount', 'verbose_name_plural': 'taxcounter'},
        ),
        migrations.RenameField(
            model_name='taxcount',
            old_name='tax_value',
            new_name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='taxcount',
            name='user',
        ),
    ]
