# Generated by Django 3.1 on 2022-10-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='subject',
        ),
    ]
