# Generated by Django 3.1 on 2022-10-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pincode',
        ),
    ]
