# Generated by Django 3.1 on 2022-10-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_taxcount_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaxCount',
        ),
    ]
